### ISSUE TITLE
xserver-xorg-input-all is installed instead of xserver-xlibre-input-all

### ISSUE THREAD

**Issue by dev-jam** [xlibre-deb/debian#12]
When creating a live debian Trixie image with live-build,  xserver-xlibre-input-* packages are not installed, but xserver-xorg-input-all and xserver-xorg-input-libinput are. This makes the system unusable due to no working mouse and keyboard. Before xlibre 7.8+3 and xserver-xlibre-common 25.0.0.9-1, everything was working correctly.  

To get the correct packages, I need: 

sudo apt install xlibre xserver-xlibre-input-all

**Comment by apebl** [comment]
That's weird. The `xserver-xlibre-input-*` packages conflict with `xserver-xorg-input-*`, so you can't install both at the same time. If you install XLibre input drivers, Xorg versions must be removed.

**Comment by apebl** [comment]
So you mean that installing `xlibre` isn't enough, and `xserver-xlibre-input-all` also needs to be specified? That shouldn't happen, because `xlibre` already depends on (`xserver-xlibre` which depends on) `xserver-xlibre-input-all`. I'm not sure about live-build, but it might install the Xorg input drivers (along with the newly added `xorg-input-abi-24-dummy` package) after `xlibre` is installed.

**Comment by apebl** [comment]
I removed `xorg-input-abi-24-dummy` from the repo (since it seemed useless), so your live image should be working again with only `xlibre`. This situation shouldn't happen anyway 🤔. It might still be better to specify all of `xlibre`, `xserver-xlibre-input-all`, and `xserver-xlibre-video-all` just to be sure.

**Comment by dev-jam** [comment]
It works better now, but i still have a bug. 

`sudo apt install xlibre`

works correctly now, no `xserver-xorg` packages.

But it does not install xserver-xlibre-input-synaptics by default. So when I use:

`sudo apt install xlibre xserver-xlibre-input-synaptics`

`xserver-xlibre-input-synaptics` is also installed but now `xserver-xlibre-input-all` and `xserver-xlibre-input-wacom` are not installed and `xserver-xorg-input-all` is installed. I can workaround this but it seems something is still not correct with the dependencies.

**Comment by apebl** [comment]
Ah, OK. I see what caused your first issue now. The `xserver-xlibre` package depends on `xserver-xlibre-input-all | xlibre-driver-input`. This means if you install a specific input driver, it won't install `xserver-xlibre-input-all` package.
